name: chapter10-dl-explain
channels:
  - conda-forge
dependencies:
  - python=3.8.10
  - pyspark=3.2.1
  - openjdk=8
  - pip
  - pip:
      - ipykernel==6.13.0
      - lightning-flash[all]==0.5.2
      - mlflow==1.25.1
      - transformers==4.9.2
      - boto3==1.19.7
      - pytorch-lightning==1.4.9
      - datasets==1.9.0
      - click==8.0.3
      - databricks-cli==0.16.2
      - gcld3==3.0.13
      - cachetools==5.0.0
      - ray[tune]==1.9.2
      - optuna==2.10.0
      - shap==0.40.0
      - ipywidgets==7.7.0
      - matplotlib==3.5.1
